name: Deploy to Debian Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip
        pip3 install -r requirements.txt

    - name: Deploy to server
      run: |
        # Replace this command with your deployment script
        ssh user@your-debian-server 'bash -s' < deploy_script.sh
